### ISSUE TITLE
BlueAir Sense+ support?

### ISSUE THREAD

**Issue by mp0505** [mylesgray/homebridge-blueair#26]
It's a very awesome and useful plugin. 
Any plans adding support of Bluair Sense device?
I've tested this plugin on Sense+ device and I could say I was able to get a basic features working. Altough there is an execption that homberidge throws from time to time. 

```
TypeError: Cannot read property 'length' of undefined
    at BlueAir.<anonymous> (/usr/lib/node_modules/homebridge-blueair/index.js:509:31)
    at BlueAir.<anonymous> (/usr/lib/node_modules/homebridge-blueair/index.js:281:6)
    at Request.self.callback (/usr/lib/node_modules/homebridge-blueair/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
```

**Comment by mlkh0225** [comment]
This is caused by homebridge requesting environmental data points from Sense, the returned null result will crash the homebridge server.
Adding a option to indicate the device is purifier only and skipping getLatestValues function if true will prevent this.
The only thing I can't quite figure out is there seem to be no way to check the remaining life of the filter, even after I changed it the initUsagePeriod value will not increase.

**Comment by Neptune-Blue** [comment]
I am quite new to github and and homebridge. Can you help me on how to exactly change the code in index.js and then upload it to my homebridge with the mentioned change above?

**Comment by mylesagray** [comment]
I’ll take a look at this today and get something out for y’all.

**Comment by Neptune-Blue** [comment]
Fantastic. Looking forward to getting the update.

Anything I can do in the meantime?

**Comment by Neptune-Blue** [comment]
Many thanks again and sorry if I’m being pushy but any chance of uploading
the update this weekend?

**Comment by mlkh0225** [comment]
You can try downloading and replaceing the index.js from my forked copy of the project if your wanna fix this now.

**Comment by Neptune-Blue** [comment]
Fantastic. Thank you for this. I was thinking of commenting out the
getLatestValue function. Now to my last question how do I get your index.js
into homebridge?

**Comment by mylesagray** [comment]
@mlkh0225 - I looked at the code in your fork, looks perfect - if you open a PR I'll get it pulled into this repo and cut a new release on NPM for everyone.

**Comment by mylesagray** [comment]
Published as v0.5.0 - do an update of the plugin and support is there now, thanks @mlkh0225

**Comment by Neptune-Blue** [comment]
Thank you again. Unfortunately, I am still getting the following error:

TypeError: Cannot read property 'length' of undefined
    at BlueAir.<anonymous> (/usr/lib/node_modules/homebridge-blueair/index.js:516:31)
    at BlueAir.<anonymous> (/usr/lib/node_modules/homebridge-blueair/index.js:288:6)
    at Request.self.callback (/usr/lib/node_modules/homebridge-blueair/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)

on the back of the following config:

            "accessory": "BlueAir",
            "name": "BlueAir Sense+",
            "airPurifierIndex": 0,
            "nameAirQuality": "Air Quality",
            "nameTemperature": "Temperature",
            "nameHumidity": "Humidity",
            "nameCO2": "Carbon Dioxide",
            "username": "rsbspamemail@gmail.com",
            "password": "XXXXXXX",
            "showTemperature": false,
            "showHumidity": false,
            "showAirQuality": false,
            "showCO2": false,
            "showLED": false,
            "getHistoricalStats": false

Any idea whats is wrong on my end?

**Comment by mylesagray** [comment]
You’ll need to adjust the config to include the purifierOnly param, is in the new Readme.md file

```json
{
    "accessory": "BlueAir",
    "name": "BlueAir Sense",
    "airPurifierIndex": 0,
    "purifierOnly": true,
    "username": "{BlueAir-Email}",
    "password": "{BlueAir-Password}",
    "showLED": false
},
```

**Comment by Neptune-Blue** [comment]
Thank you. Been just playing with it over the last hour and just realized it as well. Another small bug i found is that if you set "getHistoricalStats": true in the config it will give an error so it needs to be not set in config and left to false as per index.js.

Thank you again.

**Comment by mp0505** [comment]
@mlkh0225 thanks for the great effort fixing it. Ir works without errors on my end.

Just observed if value is set "airPurifierIndex": 1, then accessory is not responding at all. I had to set to "airPurifierIndex": 0, in order to get it working.
