### ISSUE TITLE
BlueAir Classic 205

### ISSUE THREAD

**Issue by ndoolin** [mylesgray/homebridge-blueair#31]
First and foremost thanks for all the work on this plugin!
I setup the plugin and I have both an BlueAir Aware and Classic 205.
As my Classic 205 does not have the following options.
    "nameAirQuality": "Air Quality", //optional
    "nameTemperature": "Temperature", //optional
    "nameHumidity": "Humidity", //optional
    "nameCO2": "Carbon Dioxide", //optional
I've removed those lines, so no issues there, however I don't want to show these sensors in Homekit.
In doing that I've changed these values to the the following.
            "showTemperature": false,
            "showHumidity": false,
            "showAirQuality": false,
            "showCO2": false,

When I save and attempt to restart I get the following errors and Homebridge does not start.

[7/2/2020, 08:03:47] [BlueAir 205] Initializing BlueAir accessory...
[7/2/2020, 08:03:48] TypeError: Cannot read property 'getCharacteristic' of undefined
    at new BlueAir (/usr/local/lib/node_modules/homebridge-blueair/index.js:235:5)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:357:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
 
So I need to revert back to true on the above values for All but the CO2 sensor.  If any of the other sensors are listed as false, Homebridge won't start.

Blueair Aware is working fine.  Controls of the Blueair Classic 205 is fine.  I can turn it on and off as well as adjust fan speed.

Can anyone indicate what I may be doing wrong or is this a bug?

Thanks!

-Nick

**Comment by stephenjmcmahon** [comment]
I'm able to replicate that. There is a note on the front page of this repo and maybe this is related?

_"Currently supported are all Classic i-Series air purifiers, however, Classic series without sensors but do have wifi controls, should be supportable if I can be provided with API output by anyone!"_

@mylesagray - I have a Classic 605 and am willing to help if this is related!

[7/13/2020, 4:02:23 PM] TypeError: Cannot read property 'getCharacteristic' of undefined
    at new BlueAir (/homebridge/node_modules/homebridge-blueair/index.js:235:5)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:357:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)

**Comment by mylesagray** [comment]
Hey @stephenjmcmahon you'd be right, that's the same thing - can you follow the API instructions in the Readme on the front page and post up the output here for us to have a look at?

**Comment by mylesagray** [comment]
@ndoolin - @stephenjmcmahon and I had a DM thread on Twitter and he got me a copy of his API output, should have a patch tomorrow for you to test.

**Comment by ndoolin** [comment]
Awesome!!  Thanks Guys!

-Nick

**Comment by ndoolin** [comment]
@mylesagray @stephenjmcmahon 
I modified the config and restarted homebridge and at this point the only variable that is causing me issues is ShowAirQuality when I attempt to set it to False.  Setting Temperature and Humidity to False now seems Ok.

**Comment by mylesagray** [comment]
Guys can you try setting up your config with the `purifierOnly: True` option as below?

```
{
    "accessory": "BlueAir",
    "name": "BlueAir Classic",
    "airPurifierIndex": 0,
    "purifierOnly": true,
    "username": "{BlueAir-Email}",
    "password": "{BlueAir-Password}"
}
```

**Comment by ndoolin** [comment]
Works for me!

Thank You!

-Nick

**Comment by stephenjmcmahon** [comment]
> 
> 
> Guys can you try setting up your config with the `purifierOnly: True` option as below?
> 

This works! Showed right up in Homekit!!!

How trivial would it be to flip the fan/light toggles? I stitched the shot together but you need to scroll down for the fan option :x no issues either way, important thing is us Classic boi's can automate it and forget it now !!

Time to update the readme with Classic support !!! 🎉🎉

yessssss this was the last real thing I needed, I'm over the moon!

![signal-2020-07-17-053238](https://user-images.githubusercontent.com/29905018/87786617-1b753a00-c7ef-11ea-90ce-7c0297c52d09.png)

**Comment by mylesagray** [comment]
Excellent @stephenjmcmahon ! Actually that layout isn't chosen by us, Home.app does that itself, so we have no sway there :(

I'll update the readme and close this out, thanks for the patience folks!
