### ISSUE TITLE
crashes homebridge on restart 

### ISSUE THREAD

**Issue by Gondee** [mylesgray/homebridge-blueair#32]
on a fresh install of this, seems to crash the homebridge: 
`[8/24/2020, 11:30:32 PM] TypeError: Math.max is not iterable (cannot read property Symbol(Symbol.iterator))
    at BlueAir.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/index.js:770:25)
    at BlueAir.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/index.js:691:11)
    at BlueAir.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/index.js:288:6)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)`

**Comment by mylesagray** [comment]
@Gondee what version of BlueAir do you have and can you post your config.json please?

**Comment by Gondee** [comment]
So i used the config for a i model when i have a classic model. A straight copy and paste from the front page with my credentials put in. Not sure if this warrants any investigation. My bad.
