### ISSUE TITLE
Purifier Classic 205 error

### ISSUE THREAD

**Issue by Teone55** [mylesgray/homebridge-blueair#38]
Hi, got an issue following your instructions:

TypeError: Cannot read property 'uuid' of undefined
    at BlueAir.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/index.js:375:55)
    at BlueAir.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/index.js:288:6)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)

My config is:
{
    "accessory": "BlueAir",
    "name": "BlueAir Classic",
    "airPurifierIndex": 0,
    "purifierOnly": true,
    "username": "{BlueAir-Email}",
    "password": "{BlueAir-Password}",
    "showLED": true
}

I'm doing something bad?

**Comment by robpegurri** [comment]
Hey @Teone55,

I had your same issue but I've later found out it was just a typo in my config.json (I see it in yours too). Well not exactly my typo, it's the sample config of this plugin. First of all, as with every JSON file you have to put your email and password not between { } but just " ". Moreover, the 0 of airPurifierIndex must be written as "0".

It means the right config.json snippet is:
`{ 
            "accessory": "BlueAir",
            "name": "BlueAir Sense", 
            "airPurifierIndex": "0", 
            "purifierOnly": true, 
            "username": "email@provider.com", 
            "password": "your_supersecret_psw", 
            "showLED": false 
}`

Let me know if it works!

**Comment by robpegurri** [comment]
@mylesagray you can close this issue ;)

**Comment by Teone55** [comment]
It works!
So you can close the issue, but please correct the readme doc.

**Comment by mylesagray** [comment]
Updated docs and `config-example.json`, closing 👍🏻
