### ISSUE TITLE
Support for HealthProtect

### ISSUE THREAD

**Issue by bradhs** [mylesgray/homebridge-blueair#39]
Hello, Do you know if this will work with HealthProtect models?  I can give you my u/p if you want to check it out.

**Comment by Maotiancai** [comment]
I am looking for this too! I am here to provide help if anyone could add the support for HealthProtect!

**Comment by tkundhi** [comment]
I tried the plugin with a HealthProtect 7470i and it crashes the app once you add the accessory to the configuration file. Here is the crash log.

2/20/2021, 14:46:13] TypeError: Cannot read property 'uuid' of undefined
    at BlueAir.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/index.js:375:55)
    at BlueAir.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/index.js:288:6)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)

**Comment by wgalternate** [comment]
Getting the same 'uuid' error on mine. Did you manage to get yours working by any chance?

I cant seem to get the API key for health protect as well, following the instructions that myles outlined using Charles

**Comment by Reevak05** [comment]
I'm experiencing the exact same problem with my HealthProtect 7410i. I've tried a bunch of different config field combinations which (according to other people) work with their other types of BlueAir purifiers. Has anyone made any progress with a solution?
```[04/09/2021, 21:53:25] TypeError: Cannot read property 'uuid' of undefined
    at BlueAir.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/index.js:375:55)
    at BlueAir.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/index.js:288:6)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)```

**Comment by fjs21** [comment]
Try https://github.com/fjs21/homebridge-blueair

Assuming you get the same error. Start a new issue and I will try to work on this.
