### ISSUE TITLE
This plugin slows down Homebridge

### ISSUE THREAD

**Issue by mrhsiao** [mylesgray/homebridge-blueair#43]
Homebridge version: 1.3.0
Node.js Version: v14.15.1
Npm Version: v6.14.9

This plugin slows down Homebridge. The read handler for the characteristic 'Carbon Dioxide Peak Level' was slow to respond! See https://git.io/JtMGR for more info.

**Comment by JeffGoldner** [comment]
I got rid of CO2 from the config file, no need for it as CO2 shows up as one of the 5 accessories under Air Quality for the 480i in Home.

**Comment by motaker** [comment]
Hi, I have similar error and If I got rid of CO2 entity in the config file, homebridge has booted without problem but there is several error message.
Then within a day, homebridge itself will be no responce. please help.

Error message
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Active' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Current Air Purifier State' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Target Air Purifier State' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Physical Controls' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Rotation Speed' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Change Indication' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Life Level' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Air Quality' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'PM2.5 Density' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'VOC Density' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Carbon Dioxide Level' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Air Quality PM25' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Current Relative Humidity' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Active' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Current Air Purifier State' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Target Air Purifier State' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Physical Controls' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Rotation Speed' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Change Indication' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Life Level' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:10] [homebridge-blueair] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic was supplied illegal value: number -570.5555555555555 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:18] [homebridge-blueair] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:18] [homebridge-blueair] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

My config.
        {
            "accessory": "BlueAir",
            "name": "480i",
            "airPurifierIndex": "0",
            "nameAirQuality": "Air Quality",
            "nameTemperature": "Temp.",
            "nameHumidity": "Hum.",
            "username": "email",
            "password": "password",
            "showTemperature": true,
            "showHumidity": true,
            "showAirQuality": true,
            "showLED": false,
            "getHistoricalStats": true
        },
        {
            "accessory": "BlueAir",
            "name": "205",
            "airPurifierIndex": "1",
            "purifierOnly": true,
            "username": "email",
            "password": "password",
            "showLED": false
        },

**Comment by motaker** [comment]
Hi, I have similar error, couldn't start homebridge instance itself due to this plugin.
**When I set CO2 entity and "getHistoricalStats": false in config file,
Error messages appeares in homebridge UI log file shown in red color.**

```
[29/06/2021, 21:46:32] TypeError: Cannot read property 'getCharacteristic' of undefined
at new BlueAir (/usr/local/lib/node_modules/homebridge-blueair/index.js:235:5)
at /usr/local/lib/node_modules/homebridge/src/server.ts:350:50
at Array.forEach ()
at Server.loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:29)
at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:162:12)

[29/06/2021, 21:52:35] TypeError: Cannot read property 'addEntry' of undefined
at BlueAir. (/usr/local/lib/node_modules/homebridge-blueair/index.js:567:32)
at BlueAir. (/usr/local/lib/node_modules/homebridge-blueair/index.js:288:6)
at Request.self.callback (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:185:22)
at Request.emit (events.js:375:28)
at Request. (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1154:10)
at Request.emit (events.js:375:28)
at IncomingMessage. (/usr/local/lib/node_modules/homebridge-blueair/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:481:28)
at IncomingMessage.emit (events.js:387:35)
at endReadableNT (internal/streams/readable.js:1317:12)
```

**If I got rid of CO2 entity in the config file, and set "getHistoricalStats": true,
homebridge instance has started without problem however there is several error message in white letter as shown below.**

Error message
```
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Active' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Current Air Purifier State' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Target Air Purifier State' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Physical Controls' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Rotation Speed' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Change Indication' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Life Level' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Air Quality' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'PM2.5 Density' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'VOC Density' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Carbon Dioxide Level' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Air Quality PM25' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Current Relative Humidity' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Active' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Current Air Purifier State' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Target Air Purifier State' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Physical Controls' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Rotation Speed' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Change Indication' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:07] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Life Level' was slow to respond! See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:10] [homebridge-blueair] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic was supplied illegal value: number -570.5555555555555 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:18] [homebridge-blueair] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[29/06/2021, 21:57:18] [homebridge-blueair] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

```
**First few hours seems stable but unfortunately within a day, homebridge instance will be entirely no responce. below message is shown in log as critical error in red text.**

```
[01/07/2021, 11:24:57] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Target Air Purifier State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[01/07/2021, 11:24:57] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Physical Controls' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[01/07/2021, 11:24:57] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Rotation Speed' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[01/07/2021, 11:24:57] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Change Indication' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[01/07/2021, 11:24:57] [homebridge-blueair] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Life Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

```
**Please advice.**

```
My config.
{
"accessory": "BlueAir",
"name": "480i",
"airPurifierIndex": "0",
"nameAirQuality": "Air Quality",
"nameTemperature": "Temp.",
"nameHumidity": "Hum.",
"username": "email",
"password": "password",
"showTemperature": true,
"showHumidity": true,
"showAirQuality": true,
"showLED": false,
"getHistoricalStats": true
},
{
"accessory": "BlueAir",
"name": "205",
"airPurifierIndex": "1",
"purifierOnly": true,
"username": "email",
"password": "password",
"showLED": false
},

```
Homebridge Version v1.3.4
Node.js Version v14.17.1
Npm Version v7.19.0

**Comment by paalolav** [comment]
Same issue here. Don't know how to fix this.

**Comment by fjs21** [comment]
Try the new fork. https://github.com/fjs21/homebridge-blueair

I made this to fix some of these type of errors.
